/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reto5.vista;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        Tfcodigo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Lnombre = new javax.swing.JLabel();
        Lprecio = new javax.swing.JLabel();
        Linventario = new javax.swing.JLabel();
        Tfnombre = new javax.swing.JTextField();
        Tfprecio = new javax.swing.JTextField();
        Tfinventario = new javax.swing.JTextField();
        Tfcodigo = new javax.swing.JTextField();
        Btnagregar = new javax.swing.JButton();
        Btnactualizar = new javax.swing.JButton();
        Btnborrar = new javax.swing.JButton();
        Btninforme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto 5");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 204, 204));

        Titulo.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 51, 51));
        Titulo.setText("APP de Cafeteria");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bienvenido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        Lnombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lnombre.setForeground(new java.awt.Color(255, 51, 0));
        Lnombre.setText("Nombre:");

        Lprecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lprecio.setForeground(new java.awt.Color(255, 51, 0));
        Lprecio.setText("Precio:");

        Linventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Linventario.setForeground(new java.awt.Color(255, 51, 0));
        Linventario.setText("Inventario:");

        Tfcodigo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lnombre)
                            .addComponent(Lprecio)
                            .addComponent(Linventario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tfprecio)
                            .addComponent(Tfnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(Tfinventario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(Tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lnombre))
                        .addGap(37, 37, 37)
                        .addComponent(Tfinventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lprecio)
                            .addComponent(Tfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Linventario)))
                .addContainerGap())
        );

        Btnagregar.setBackground(new java.awt.Color(102, 102, 102));
        Btnagregar.setForeground(new java.awt.Color(255, 0, 0));
        Btnagregar.setText("Agregar Producto");

        Btnactualizar.setBackground(new java.awt.Color(102, 102, 102));
        Btnactualizar.setForeground(new java.awt.Color(255, 0, 0));
        Btnactualizar.setText("Actualizar Producto");

        Btnborrar.setBackground(new java.awt.Color(102, 102, 102));
        Btnborrar.setForeground(new java.awt.Color(255, 0, 0));
        Btnborrar.setText("Borrar Producto");

        Btninforme.setBackground(new java.awt.Color(102, 102, 102));
        Btninforme.setForeground(new java.awt.Color(255, 0, 0));
        Btninforme.setText("Informe");

        Tabla.setBackground(new java.awt.Color(153, 153, 153));
        Tabla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Tabla.setForeground(new java.awt.Color(255, 0, 51));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Inventario"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btninforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnagregar)
                    .addComponent(Btnactualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btninforme)
                    .addComponent(Btnborrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnactualizar;
    private javax.swing.JButton Btnagregar;
    private javax.swing.JButton Btnborrar;
    private javax.swing.JButton Btninforme;
    private javax.swing.JLabel Linventario;
    private javax.swing.JLabel Lnombre;
    private javax.swing.JLabel Lprecio;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Tfcodigo;
    private javax.swing.JTextField Tfinventario;
    private javax.swing.JTextField Tfnombre;
    private javax.swing.JTextField Tfprecio;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnactualizar() {
        return Btnactualizar;
    }

    public void setBtnactualizar(JButton Btnactualizar) {
        this.Btnactualizar = Btnactualizar;
    }

    public JButton getBtnagregar() {
        return Btnagregar;
    }

    public void setBtnagregar(JButton Btnagregar) {
        this.Btnagregar = Btnagregar;
    }

    public JButton getBtnborrar() {
        return Btnborrar;
    }

    public void setBtnborrar(JButton Btnborrar) {
        this.Btnborrar = Btnborrar;
    }

    public JButton getBtninforme() {
        return Btninforme;
    }

    public void setBtninforme(JButton Btninforme) {
        this.Btninforme = Btninforme;
    }

    public JTextField getTfcodigo() {
        return Tfcodigo;
    }

    public void setTfcodigo(JTextField Tfcodigo) {
        this.Tfcodigo = Tfcodigo;
    }

    public JTextField getTfinventario() {
        return Tfinventario;
    }

    public void setTfinventario(JTextField Tfinventario) {
        this.Tfinventario = Tfinventario;
    }

    public JTextField getTfnombre() {
        return Tfnombre;
    }

    public void setTfnombre(JTextField Tfnombre) {
        this.Tfnombre = Tfnombre;
    }

    public JTextField getTfprecio() {
        return Tfprecio;
    }

    public void setTfprecio(JTextField Tfprecio) {
        this.Tfprecio = Tfprecio;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTabla() {
        return Tabla;
    }

    public void setTabla(JTable Tabla) {
        this.Tabla = Tabla;
    }
}
